name: Laravel CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0  # Adjust MySQL version if needed
        env:
          MYSQL_ROOT_PASSWORD: root  # Replace with a secure password
          MYSQL_DATABASE: fighton  # Customize database name

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust PHP version based on your Laravel requirements

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Grant storage permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Configure Database Connection
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: fighton  # Matches the service name
          DB_USERNAME: root
          DB_PASSWORD: root  # Access secret password
          DB_PORT: 3306
        run: php artisan migrate:fresh --seeder=DatabaseSeeder

      - name: Run Tests
        run: php artisan test

